fix(clerk.js): Don't duplicate the protocol separator while producing the request URL, for issue #1209
clerkinc/javascript pull request #1210
Opened 2023-05-19 21:45 UTC by brunoschmidt

## Type of change

- [X] 🐛 Bug fix

## Packages affected

- [X] `@clerk/nextjs`

## Description

- [X] `npm test` runs as expected.
- [X] `npm run build` runs as expected.

Small fix to not duplicate the comma separating the protocol, when there is no "X-Forwarded-Host" header.

Fixes #1209

2023-05-20 09:44 UTC, panteliselef requested changes

2023-05-20 09:44 UTC, panteliselef commented on packages/nextjs/src/server/utils.ts
> +    (headers.get('X-Forwarded-Proto') ?? (headers as any)['X-Forwarded-Proto'])?.split(',')[0] ?? (url.protocol && url.protocol.slice(0, -1));
This feels more robust, thanks for raising this 😀
```suggestion
    (headers.get('X-Forwarded-Proto') ?? (headers as any)['X-Forwarded-Proto'])?.split(',')[0] ?? (url.protocol && url.protocol.replace(/\:$/, '');
```

2023-05-22 10:28 UTC, panteliselef commented on packages/nextjs/src/server/utils.ts
> +    (headers.get('X-Forwarded-Proto') ?? (headers as any)['X-Forwarded-Proto'])?.split(',')[0] ?? (url.protocol && url.protocol.replace(/\:$/, '');
🔧  Please add a parenthesis at the end of the line 
```suggestion
    (headers.get('X-Forwarded-Proto') ?? (headers as any)['X-Forwarded-Proto'])?.split(',')[0] ?? (url.protocol && url.protocol.replace(/\:$/, ''));
```

2023-05-23 07:31 UTC, panteliselef commented
@brunoschmidt  could you please squash and rebase 🙃

2023-05-23 08:38 UTC, nikosdouvlis commented
No need to rebase or anything, I will go ahead and merge this so we can get it out with our next release.
Many thanks for the contribution @brunoschmidt :)

2023-05-23 08:38 UTC, merged