Increase parity between dev and prod instances when triggering sync/link
clerkinc/javascript pull request #1402
Opened 2023-06-22 13:38 UTC by panteliselef

## Type of change

- [ ] 🐛 Bug fix
- [ ] 🌟 New feature
- [ ] 🔨 Breaking change
- [x] 📖 Refactoring / dependency upgrade / documentation
- [ ] other:

## Packages affected

- [x] `@clerk/clerk-js`
- [ ] `@clerk/clerk-react`
- [ ] `@clerk/nextjs`
- [ ] `@clerk/remix`
- [ ] `@clerk/types`
- [ ] `@clerk/themes`
- [ ] `@clerk/localizations`
- [ ] `@clerk/clerk-expo`
- [x] `@clerk/backend`
- [ ] `@clerk/clerk-sdk-node`
- [ ] `@clerk/shared`
- [ ] `@clerk/fastify`
- [ ] `@clerk/chrome-extension`
- [ ] `gatsby-plugin-clerk`
- [ ] `build/tooling/chore`

## Description

- [x] `npm test` runs as expected.
- [x] `npm run build` runs as expected.

2023-06-26 09:42 UTC, SokratisVidros requested changes

2023-06-26 09:42 UTC, SokratisVidros commented on packages/clerk-js/src/core/clerk.ts
> +     * At this point the devBrowser is not yet setup, but its API is ready for use
@panteliselef let's explain why this step is required in the comment. If not mistake the devBrowserHandler is used by some multi-domain helpers. This should be stated explicitly.

2023-06-26 09:42 UTC, SokratisVidros commented on packages/clerk-js/src/core/clerk.ts
> +     * At this point we have already attempted to pre-populate devBrowser with a fresh JWT, if Step 3 was successful this will not be overwritten
Please also elaborate on this by stating that in a satellite app we don't want to get the JWT from FAPI but from URL Based Session Syncing as we are trying to sync the primary and satellite dev browser values.

2023-06-29 09:02 UTC, nikosdouvlis reviewed
Good work @panteliselef 
I'll do another pass as this requires more time, but this makes more sense now

2023-06-29 09:24 UTC, panteliselef commented on packages/clerk-js/src/core/clerk.ts
> +    // TODO: Remove this in the minor release
We need this PR to go out in a prod release, everyone to use that new version, and then remove the code marked with this comments. Does that sound ok ?

2023-06-29 09:47 UTC, nikosdouvlis commented on packages/clerk-js/src/core/clerk.ts
> +    // TODO: Remove this in the minor release
How are we keeping track of who used this at least once? Do we need to?

2023-06-29 10:45 UTC, panteliselef commented on packages/clerk-js/src/core/clerk.ts
> +    // TODO: Remove this in the minor release
I don't think we need to. 

Everything marked as deprecated there will only affect development instances. So no worries about breaking clients.
I believe with the new way we deliver clerk-js once we release a version everyone will get it quickly.

And regarding to the changes made in the backend package, we will not mind if the will be using the old version as long as the run the latest clerk-js (this flow is driven by clerk-js)

2023-06-29 21:00 UTC, SokratisVidros approved these changes

2023-07-03 10:16 UTC, nikosdouvlis approved these changes

2023-07-03 14:39 UTC, merged

2024-07-03 00:01 UTC, clerk-cookie commented
This PR has been automatically locked since there has not been any recent activity after it was closed. Please open a new issue for related bugs.