feat(localizations): Add el-GR localization
clerkinc/javascript pull request #1479
Opened 2023-07-12 23:59 UTC by EmmanouelaPothitou

## Type of change

- [ ] 🐛 Bug fix
- [ ] 🌟 New feature
- [ ] 🔨 Breaking change
- [ ] 📖 Refactoring / dependency upgrade / documentation
- [ ] other:

## Packages affected

- [ ] `@clerk/clerk-js`
- [ ] `@clerk/clerk-react`
- [ ] `@clerk/nextjs`
- [ ] `@clerk/remix`
- [ ] `@clerk/types`
- [ ] `@clerk/themes`
- [ ] `@clerk/localizations`
- [ ] `@clerk/clerk-expo`
- [ ] `@clerk/backend`
- [ ] `@clerk/clerk-sdk-node`
- [ ] `@clerk/shared`
- [ ] `@clerk/fastify`
- [ ] `@clerk/chrome-extension`
- [ ] `gatsby-plugin-clerk`
- [ ] `build/tooling/chore`

## Description

- [ ] `npm test` runs as expected.
- [ ] `npm run build` runs as expected.

Add el-GR localization

2023-07-13 09:22 UTC, raptisj commented on packages/localizations/src/el-GR.ts
> +  badge__otherImpersonatorDevice: 'Άλλη συσκευή αντιπροσώπου',
@EmmanouelaPothitou Not sure if "αντιπροσώπου" is right here. This translates to "representative". 
I think "Άλλη συσκευή υποδυόμενου" is better. WDYT?

2023-07-13 09:23 UTC, raptisj commented on packages/localizations/src/el-GR.ts
> +      resendButton: 'Δεν λάβατε έναν κωδικό; Επανάληψη αποστολής',
@EmmanouelaPothitou I think we can omit the "εναν" here. 
Result: "Δεν λάβατε κωδικό; Επανάληψη αποστολής"

2023-07-13 09:24 UTC, raptisj requested changes
@EmmanouelaPothitou Awesome 🎉 Thank you for your contribution. I left some comments, please have a look. 

Also, you will need to add a changeset file with a brief summary of what this PR is doing. For more information regarding changeset read [this](https://github.com/clerkinc/javascript/blob/main/docs/CONTRIBUTING.md#changesets).

2023-07-13 09:28 UTC, raptisj commented on packages/localizations/src/el-GR.ts
> +      subtitle: 'Προσκαλέστε νέα μέλη σε αυτόν τον οργανισμόη',
@EmmanouelaPothitou small typo "οργανισμόη" here

2023-07-13 09:33 UTC, raptisj commented on packages/localizations/src/el-GR.ts
> +      'Η εγγραφή απέτυχε λόγω αποτυχημένων ελέγχων ασφαλείας. Ανανεώστε τη σελίδα για να δοκιμάσετε ξανά ή επικοινωνήστε με την υποστήριξη για περισσότερη βοήθεια.',
@EmmanouelaPothitou "...επικοινωνήστε με την υποστήριξη..." could become "...επικοινωνήστε με το κέντρο υποστήριξης..."

2023-07-13 09:35 UTC, raptisj commented on packages/localizations/src/el-GR.ts
> +    form_password_validation_failed: 'Incorrect Password',
@EmmanouelaPothitou maybe your intention was "Λανθασμένος κωδικός" here?

2023-07-13 09:41 UTC, raptisj commented on packages/localizations/src/el-GR.ts
> +        dates: 'Ημερομηνίες είναι εύκολο να μαντευτούν.',
@EmmanouelaPothitou I think "...είναι εύκολες να.." is the right one. WDYT?

2023-07-13 09:43 UTC, raptisj commented on packages/localizations/src/el-GR.ts
> +        capitalization: 'Μην έχετε κεφαλαίο μόνο το πρώτο γράμμα .',
@EmmanouelaPothitou 🙃 omit space after the last letter.

2023-07-14 12:14 UTC, raptisj commented on packages/localizations/src/el-GR.ts
> +  footerPageLink__privacy: 'Προστασία προσωπικών δεδομένων ',
@EmmanouelaPothitou omit space here

2023-07-14 12:21 UTC, raptisj commented on packages/localizations/src/el-GR.ts
> +      formSubtitle: 'Εισαγάγετε τον κωδικό επαλήθευσης που απεστάλη στη διεύθυνση email σας',
@EmmanouelaPothitou I think "Εισάγετε τον κωδικό επαλήθευσης που απεστάλη στο email σας" is better. WDYT?

or alternatively
"Εισάγετε τον κωδικό επαλήθευσης που απεστάλη σε αυτή την διεύθυνση"

2023-07-14 12:28 UTC, raptisj commented on packages/localizations/src/el-GR.ts
> +      successMessage: 'Ο κωδικός πρόσβασής σας αλλάχθηκε με επιτυχία. Σας συνδέουμε, παρακαλώ περιμένετε.',
@EmmanouelaPothitou "Ο κωδικός πρόσβασής σας έχει αλλάξει με ..."

2023-07-14 12:31 UTC, raptisj commented on packages/localizations/src/el-GR.ts
> +          'Εάν αντιμετωπίζετε δυσκολία στη σύνδεση στον λογαριασμό σας, στείλτε μας email και θα συνεργαστούμε μαζί σας για να αποκαταστήσουμε την πρόσβαση το συντομότερο δυνατόν.',
@EmmanouelaPothitou "και θα επικοινωνήσουμε...." instead of "και θα συνεργαστούμε...."

2023-07-14 12:44 UTC, raptisj commented on packages/localizations/src/el-GR.ts
> +    fileDropAreaHint: 'Ανεβάστε μια εικόνα σε μορφή JPG, PNG, GIF ή WEBP μικρότερη από 10 MB',
@EmmanouelaPothitou "...μικρότερη των 10 MB" WDYT?

2023-07-14 12:46 UTC, raptisj commented on packages/localizations/src/el-GR.ts
> +      resendButton: 'Δεν λάβατε ένα σύνδεσμο; Επανάληψη αποστολής',
@EmmanouelaPothitou I think this sounds better. "Δεν λάβατε κάποιον σύνδεσμο;"

2023-07-14 12:56 UTC, raptisj commented on packages/localizations/src/el-GR.ts
> +      'Δεν υπάρχουν διαθέσιμοι αριθμοί τηλεφώνου για εγγραφή στη διπλή επαλήθευση με κωδικούς SMS.',
@EmmanouelaPothitou "...στην διπλή επαλήθευση..."

2023-07-14 12:59 UTC, raptisj commented on packages/localizations/src/el-GR.ts
> +      successMessage: 'Η οργάνωση έχει ενημερωθεί.',
@EmmanouelaPothitou "Ο οργανισμός έχει ενημερωθεί."

2023-07-14 13:03 UTC, raptisj commented on packages/localizations/src/el-GR.ts
> +          messageLine2: 'Αυτή η ενέργεια είναι μόνιμη και ανεπανόρθωτη.',
@EmmanouelaPothitou I think this sounds better. "Αυτή η ενέργεια είναι μόνιμη και μη αναστρέψιμη"

2023-07-14 15:23 UTC, EmmanouelaPothitou commented
@raptisj I've updated the translations based on you comments, thanks! :)

2023-07-17 07:02 UTC, merged

2024-07-17 00:01 UTC, clerk-cookie commented
This PR has been automatically locked since there has not been any recent activity after it was closed. Please open a new issue for related bugs.