Apply deprecation warnings fastify
clerkinc/javascript pull request #1759
Opened 2023-09-21 18:17 UTC by dimkl

## Description

Warn about deprecations of the following environment variables in Clerk Fastify plugin:
- CLERK_API_KEY
- CLERK_FRONTEND_API

## Checklist

- [x] `npm test` runs as expected.
- [x] `npm run build` runs as expected.
- [x] (If applicable) [JSDoc comments](https://jsdoc.app/about-getting-started.html) have been added or updated for any package exports
- [x] (If applicable) [Documentation](https://github.com/clerkinc/clerk-docs) has been updated

## Type of change

- [ ] 🐛 Bug fix
- [ ] 🌟 New feature
- [ ] 🔨 Breaking change
- [x] 📖 Refactoring / dependency upgrade / documentation
- [ ] other:

## Packages affected

- [ ] `@clerk/clerk-js`
- [ ] `@clerk/clerk-react`
- [ ] `@clerk/nextjs`
- [ ] `@clerk/remix`
- [ ] `@clerk/types`
- [ ] `@clerk/themes`
- [ ] `@clerk/localizations`
- [ ] `@clerk/clerk-expo`
- [ ] `@clerk/backend`
- [ ] `@clerk/clerk-sdk-node`
- [ ] `@clerk/shared`
- [x] `@clerk/fastify`
- [ ] `@clerk/chrome-extension`
- [ ] `gatsby-plugin-clerk`
- [ ] `build/tooling/chore`

2023-09-22 09:27 UTC, anagstef requested changes

2023-09-22 09:27 UTC, anagstef commented on package-lock.json
I think we should drop the changes from this file

2023-09-22 09:32 UTC, dimkl commented on package-lock.json
@anagstef Since we've added `@clerk/shared` as dependency to the `@clerk/fastify` shouldn't the `package-lock.json` be updated? What are your concerns?

2023-09-22 09:48 UTC, anagstef commented on package-lock.json
@dimkl the root `package-lock.json` is updated automatically by our CI. Right, @nikosdouvlis ?

2023-09-22 13:18 UTC, nikosdouvlis commented on package-lock.json
@anagstef I will get back to you about that as I need to check a few things.
@dimkl I'm going to resolve this thread, please rebase, update the lockfile and merge this

2023-09-22 14:28 UTC, anagstef approved these changes

2023-09-22 15:11 UTC, merged

2024-09-22 00:01 UTC, clerk-cookie commented
This PR has been automatically locked since there has not been any recent activity after it was closed. Please open a new issue for related bugs.