chore(repo): Scoping Turborepo task inputs
clerkinc/javascript pull request #1882
Opened 2023-10-14 18:13 UTC by tmilewski

## Description

Speed up DX by scoping down the Turborepo inputs on particular tasks.

As-is, any changed file in a package results in Turborepo marking that package as altered. That slows down the DX as it requires a task (and, potentially, dependent tasks) to be re-run every time.

This PR ensures that only the relevant files are considered when Turborepo is making that determination.

### Use-Cases:

There are a number of useful cases for this, like speeding up the turnaround time for developers running tasks like `npm run test`.

### Example:

You're testing a change you made to `@clerk/clerk-sdk-node` directly and your editing only your tests.

#### Current

You run `npm run test -- --filter=@clerk/clerk-sdk-node`:

Because all files are considered for the dependent `build` task, it's also re-run:

- `@clerk/clerk-sdk-node:build` (runs)
- `@clerk/clerk-sdk-node:test` (runs)

#### New

You run `npm run test -- --filter=@clerk/clerk-sdk-node`:

Because only required files are considered for the dependent `build`, it isn't re-run:

- `@clerk/clerk-sdk-node:build` (cached)
- `@clerk/clerk-sdk-node:test` (runs)

### Results

This convoluted example might not seem like much, but it all adds up, especially, when the dependent tasks are further up the dependency graph.

## Checklist

- [x] `npm test` runs as expected.
- [x] `npm run build` runs as expected.
- [ ] (If applicable) [JSDoc comments](https://jsdoc.app/about-getting-started.html) have been added or updated for any package exports
- [ ] (If applicable) [Documentation](https://github.com/clerkinc/clerk-docs) has been updated

## Type of change

- [ ] 🐛 Bug fix
- [ ] 🌟 New feature
- [ ] 🔨 Breaking change
- [x] 📖 Refactoring / dependency upgrade / documentation
- [ ] other:

## Packages affected

- [ ] `@clerk/clerk-js`
- [ ] `@clerk/clerk-react`
- [ ] `@clerk/nextjs`
- [ ] `@clerk/remix`
- [ ] `@clerk/types`
- [ ] `@clerk/themes`
- [ ] `@clerk/localizations`
- [ ] `@clerk/clerk-expo`
- [ ] `@clerk/backend`
- [ ] `@clerk/clerk-sdk-node`
- [ ] `@clerk/shared`
- [ ] `@clerk/fastify`
- [ ] `@clerk/chrome-extension`
- [ ] `gatsby-plugin-clerk`
- [x] `build/tooling/chore`

2023-10-16 06:20 UTC, LekoArts requested changes
Small typo

2023-10-16 06:20 UTC, LekoArts commented on package.json
> +    "release:snapshot": "TURBO_FORCE=true ORCE_COLOR=1 npm run build && npx changeset publish --tag snapshot --no-git-tag",
```suggestion
    "release:snapshot": "TURBO_FORCE=true FORCE_COLOR=1 npm run build && npx changeset publish --tag snapshot --no-git-tag",
```

2023-10-17 18:28 UTC, BRKalow reviewed
I love that you're using the per-workspace `turbo.json` files here!

2023-10-17 19:07 UTC, tmilewski commented on package.json
> +    "release:snapshot": "TURBO_FORCE=true ORCE_COLOR=1 npm run build && npx changeset publish --tag snapshot --no-git-tag",
Fixed, TY!

2023-10-18 07:42 UTC, LekoArts commented on package.json
> +    "changeset": "npx changeset",
If we're changing this file that much anyways, can we remove the `npx` in favor of just calling the scripts like I did here?
https://github.com/clerkinc/javascript/pull/1891#discussion_r1361591281

Then I won't need to deal that much with merge conflicts and the change might actually make more sense in this PR anyways

2023-10-19 03:37 UTC, BRKalow reviewed
One question about the `dependsOn` change for `lint`, otherwise this looks pretty good. Nice improvement!

2023-10-19 03:45 UTC, tmilewski commented on turbo.json
> +      "dependsOn": ["^build"],
@BRKalow Both work; it's just that we technically don't need to build the _current_ package.

2023-10-19 03:46 UTC, BRKalow approved these changes

2023-10-19 03:56 UTC, merged

2024-10-19 00:01 UTC, clerk-cookie commented
This PR has been automatically locked since there has not been any recent activity after it was closed. Please open a new issue for related bugs.