chore(clerk-js): Deprecate FormControl
clerkinc/javascript pull request #1912
Opened 2023-10-18 10:49 UTC by panteliselef

## Description

This is PR starts the refactoring process for our forms. The main focus is refactoring how our fields are structure, starting the `PlainInput` which represents a simple input element.

- Replace Form.Control with Form.PlainInput (example usage)
- Top level API remains simple, but the internally Form.PlainInput is very modular.
- Renaming contexts and hooks with the `field` prefix in order to clearly indicate that the internal state reflects to a field not the entire form
  - `FormFieldContextProvider` replaces `FormControlContextProvider` (both need to co-exist until the refactor is complete)
- Force the usage of isDisabled, isRequired over the native html attributes

## Checklist

- [x] `npm test` runs as expected.
- [x] `npm run build` runs as expected.
- [ ] (If applicable) [JSDoc comments](https://jsdoc.app/about-getting-started.html) have been added or updated for any package exports
- [ ] (If applicable) [Documentation](https://github.com/clerkinc/clerk-docs) has been updated

## Type of change

- [ ] 🐛 Bug fix
- [ ] 🌟 New feature
- [ ] 🔨 Breaking change
- [x] 📖 Refactoring / dependency upgrade / documentation
- [ ] other:

## Packages affected

- [ ] `@clerk/clerk-js`
- [ ] `@clerk/clerk-react`
- [ ] `@clerk/nextjs`
- [ ] `@clerk/remix`
- [ ] `@clerk/types`
- [ ] `@clerk/themes`
- [ ] `@clerk/localizations`
- [ ] `@clerk/clerk-expo`
- [ ] `@clerk/backend`
- [ ] `@clerk/clerk-sdk-node`
- [ ] `@clerk/shared`
- [ ] `@clerk/fastify`
- [ ] `@clerk/chrome-extension`
- [ ] `gatsby-plugin-clerk`
- [ ] `build/tooling/chore`

2023-10-25 17:43 UTC, desiprisg commented on packages/clerk-js/src/ui/elements/FieldControl.tsx
> +  AsOptional: FieldOptionalLabel,
Maybe rename this to `OptionalLabel` ?

2023-10-25 21:53 UTC, anagstef commented on packages/clerk-js/src/ui/components/SignUp/SignUpForm.tsx
> +              isDisabled={true}
@panteliselef remember to remove this one.

2023-10-25 21:55 UTC, anagstef commented on packages/clerk-js/src/ui/elements/FieldControl.tsx
> +export const Root = (props: PropsWithChildren<FormControlProps>) => {
Remove the `export`

2023-10-25 22:08 UTC, anagstef commented on packages/clerk-js/src/ui/elements/RadioGroup.tsx
> + * @deprecated
Remove the `@deprecated` until we have a replacement.

2023-10-25 22:08 UTC, anagstef commented on packages/clerk-js/src/ui/elements/RadioGroup.tsx
> + * @deprecated
Remove the `@deprecated` until we have a replacement.

2023-10-25 22:13 UTC, anagstef commented on packages/clerk-js/src/ui/primitives/hooks/useFormControl.tsx
> +    inputProps[key] = obj[key];
We should cast instead of `ts-ignore`

2023-10-25 22:14 UTC, anagstef requested changes
@panteliselef great stuff! just commit the changes we talked about and it's good to go.

2023-10-26 19:19 UTC, anagstef approved these changes
💯

2023-10-31 11:36 UTC, dimkl reviewed
Let's add the deprecation of the FormControl in the `main-v4` branch and open a clean-up PR from the main.

2023-10-31 11:37 UTC, desiprisg approved these changes

2023-10-31 11:40 UTC, dimkl commented on packages/sdk-node/src/clerkClient.ts
> +export const ClerkExpressRequireAuth = (...args: Parameters<ReturnType<typeof createClerkExpressRequireAuth>>) => {
no! Should be dropped from this PR

2023-10-31 17:27 UTC, panteliselef commented on packages/sdk-node/src/clerkClient.ts
> +export const ClerkExpressRequireAuth = (...args: Parameters<ReturnType<typeof createClerkExpressRequireAuth>>) => {
This is now dropped 🔥

2023-10-31 17:35 UTC, merged