fix(clerk-js): Correct initial ref value for form feedback
clerkinc/javascript pull request #1937
Opened 2023-10-25 17:16 UTC by desiprisg

## Description

## Checklist

- [ ] `npm test` runs as expected.
- [ ] `npm run build` runs as expected.
- [ ] (If applicable) [JSDoc comments](https://jsdoc.app/about-getting-started.html) have been added or updated for any package exports
- [ ] (If applicable) [Documentation](https://github.com/clerkinc/clerk-docs) has been updated

## Type of change

- [ ] 🐛 Bug fix
- [ ] 🌟 New feature
- [ ] 🔨 Breaking change
- [ ] 📖 Refactoring / dependency upgrade / documentation
- [ ] other:

## Packages affected

- [ ] `@clerk/clerk-js`
- [ ] `@clerk/clerk-react`
- [ ] `@clerk/nextjs`
- [ ] `@clerk/remix`
- [ ] `@clerk/types`
- [ ] `@clerk/themes`
- [ ] `@clerk/localizations`
- [ ] `@clerk/clerk-expo`
- [ ] `@clerk/backend`
- [ ] `@clerk/clerk-sdk-node`
- [ ] `@clerk/shared`
- [ ] `@clerk/fastify`
- [ ] `@clerk/chrome-extension`
- [ ] `gatsby-plugin-clerk`
- [ ] `build/tooling/chore`

2023-10-25 17:18 UTC, anagstef requested changes
Just add a changeset

2023-10-25 17:18 UTC, anagstef commented on .changeset/breezy-bikes-grin.md
> +---
Please add an entry to the changeset

2023-10-25 17:21 UTC, anagstef approved these changes

2023-10-25 17:27 UTC, octoper approved these changes

2023-10-25 19:12 UTC, dimkl commented
Closing this one as we have pushed the commit in the main-v4

2023-10-25 19:12 UTC, closed without merging

2024-10-25 00:01 UTC, clerk-cookie commented
This PR has been automatically locked since there has not been any recent activity after it was closed. Please open a new issue for related bugs.