feat(clerk-js,clerk-react,types): Introduce useOrganization, useOrgan…
clerkinc/javascript pull request #285
Opened 2022-06-08 15:20 UTC by igneel64

…izationList v2

## Type of change

- [ ] 🐛 Bug fix
- [ ] 🌟 New feature
- [ ] 🔨 Breaking change
- [ ] 📖 Refactoring / dependency upgrade / documentation
- [ ] other:

## Packages affected

- [ ] `@clerk/clerk-js`
- [ ] `@clerk/clerk-react`
- [ ] `@clerk/nextjs`
- [ ] `@clerk/remix`
- [ ] `@clerk/types`
- [ ] `@clerk/clerk-expo`
- [ ] `@clerk/backend-core`
- [ ] `@clerk/clerk-sdk-node`
- [ ] `@clerk/edge`
- [ ] `build/tooling/chore`

## Description

- [ ] `npm test` runs as expected.
- [ ] `npm run build` runs as expected.

2022-06-09 21:21 UTC, colinclerk requested changes
I don't think we should move forward with this strategy for reactivity.  We don't have a good abstraction for managing `lastOrganizationInvitation` and `lastOrganizationMembership` and it's evident from the repeated usage of `__unstable__`.

Instead, can we add something to BaseResource._fetch that triggers revalidations after any POST completes?

2022-06-09 21:21 UTC, colinclerk commented on packages/react/src/hooks/useOrganization.ts
> +  return {
Can we block until `invitationList` and `membershipList` are loaded?

I believe this allows `isLoaded: true` while `invitationList` and `membershipList` are still loading.

2022-06-15 14:48 UTC, igneel64 commented
Discussed in length offline, the functionality presented is fully reactive and the API fits the use-cases as specified.
The fixes on the mechanism, since internal, would be addressed at https://www.notion.so/clerkdev/Improve-reactivity-mechanism-of-clerk-js-clients-0ed49f1cb005473ead6245d41276f26e

2022-06-15 17:38 UTC, nikosdouvlis approved these changes

2022-06-16 07:00 UTC, merged